[build]
  # Indique à Netlify d'aller dans le dossier "client" avant de faire quoi que ce soit
  base = "client"
  
  # Le dossier où Vite va créer le site (relatif au dossier "base")
  publish = "dist"
  
  # La commande pour construire le site
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200