[build]
  # 1. On dit à Netlify : "Tout se passe dans le dossier client"
  base = "client"
  
  # 2. Une fois dans client, le dossier de sortie est "dist"
  publish = "dist"
  
  # 3. La commande pour construire le site
  command = "npm run build"

# 4. On redirige tout vers index.html pour gérer le routing React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 5. (Optionnel mais recommandé vu vos logs) On désactive l'auto-détection Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    disabled = true