[build]
  # On dit à Netlify d'entrer dans le dossier client
  base = "client"
  
  # La commande pour construire le site
  command = "npm run build"
  
  # Le dossier où Vite crée le site (relatif au dossier client)
  publish = "dist"

# Redirections pour que le routing React fonctionne (évite les 404 au refresh)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200